//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.02.05 at 11:09:28 AM EST 
//


package vroom.common.modeling.vrprep;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice>
 *         &lt;element name="avg" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *         &lt;sequence>
 *           &lt;element name="speedInterval" maxOccurs="unbounded">
 *             &lt;complexType>
 *               &lt;complexContent>
 *                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                   &lt;sequence>
 *                     &lt;element name="speed" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *                     &lt;element ref="{}tw" maxOccurs="unbounded"/>
 *                   &lt;/sequence>
 *                 &lt;/restriction>
 *               &lt;/complexContent>
 *             &lt;/complexType>
 *           &lt;/element>
 *         &lt;/sequence>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "avg",
    "speedInterval"
})
@XmlRootElement(name = "speedProfile")
public class SpeedProfile {

    protected Double avg;
    protected List<SpeedProfile.SpeedInterval> speedInterval;

    /**
     * Gets the value of the avg property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getAvg() {
        return avg;
    }

    /**
     * Sets the value of the avg property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setAvg(Double value) {
        this.avg = value;
    }

    /**
     * Gets the value of the speedInterval property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the speedInterval property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSpeedInterval().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SpeedProfile.SpeedInterval }
     * 
     * 
     */
    public List<SpeedProfile.SpeedInterval> getSpeedInterval() {
        if (speedInterval == null) {
            speedInterval = new ArrayList<SpeedProfile.SpeedInterval>();
        }
        return this.speedInterval;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="speed" type="{http://www.w3.org/2001/XMLSchema}double"/>
     *         &lt;element ref="{}tw" maxOccurs="unbounded"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "speed",
        "tw"
    })
    public static class SpeedInterval {

        protected double speed;
        @XmlElement(required = true)
        protected List<Tw> tw;

        /**
         * Gets the value of the speed property.
         * 
         */
        public double getSpeed() {
            return speed;
        }

        /**
         * Sets the value of the speed property.
         * 
         */
        public void setSpeed(double value) {
            this.speed = value;
        }

        /**
         * Time window at which this speed should be used Gets the value of the tw property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the tw property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getTw().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Tw }
         * 
         * 
         */
        public List<Tw> getTw() {
            if (tw == null) {
                tw = new ArrayList<Tw>();
            }
            return this.tw;
        }

    }

}
