//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.04.23 at 03:15:41 PM EST 
//


package vroom.common.modeling.vrprep;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice>
 *         &lt;element name="euclidean">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="cx" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *                   &lt;element name="cy" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *                   &lt;element name="cz" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="GPSCoordinates">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;attribute name="lat" use="required" type="{http://www.w3.org/2001/XMLSchema}double" />
 *                 &lt;attribute name="lon" use="required" type="{http://www.w3.org/2001/XMLSchema}double" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element ref="{}custom"/>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "euclidean",
    "gpsCoordinates",
    "custom"
})
@XmlRootElement(name = "location")
public class Location {

    protected Location.Euclidean euclidean;
    @XmlElement(name = "GPSCoordinates")
    protected Location.GPSCoordinates gpsCoordinates;
    protected Custom custom;

    /**
     * Gets the value of the euclidean property.
     * 
     * @return
     *     possible object is
     *     {@link Location.Euclidean }
     *     
     */
    public Location.Euclidean getEuclidean() {
        return euclidean;
    }

    /**
     * Sets the value of the euclidean property.
     * 
     * @param value
     *     allowed object is
     *     {@link Location.Euclidean }
     *     
     */
    public void setEuclidean(Location.Euclidean value) {
        this.euclidean = value;
    }

    /**
     * Gets the value of the gpsCoordinates property.
     * 
     * @return
     *     possible object is
     *     {@link Location.GPSCoordinates }
     *     
     */
    public Location.GPSCoordinates getGPSCoordinates() {
        return gpsCoordinates;
    }

    /**
     * Sets the value of the gpsCoordinates property.
     * 
     * @param value
     *     allowed object is
     *     {@link Location.GPSCoordinates }
     *     
     */
    public void setGPSCoordinates(Location.GPSCoordinates value) {
        this.gpsCoordinates = value;
    }

    /**
     * Gets the value of the custom property.
     * 
     * @return
     *     possible object is
     *     {@link Custom }
     *     
     */
    public Custom getCustom() {
        return custom;
    }

    /**
     * Sets the value of the custom property.
     * 
     * @param value
     *     allowed object is
     *     {@link Custom }
     *     
     */
    public void setCustom(Custom value) {
        this.custom = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="cx" type="{http://www.w3.org/2001/XMLSchema}double"/>
     *         &lt;element name="cy" type="{http://www.w3.org/2001/XMLSchema}double"/>
     *         &lt;element name="cz" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "cx",
        "cy",
        "cz"
    })
    public static class Euclidean {

        protected double cx;
        protected double cy;
        protected Double cz;

        /**
         * Gets the value of the cx property.
         * 
         */
        public double getCx() {
            return cx;
        }

        /**
         * Sets the value of the cx property.
         * 
         */
        public void setCx(double value) {
            this.cx = value;
        }

        /**
         * Gets the value of the cy property.
         * 
         */
        public double getCy() {
            return cy;
        }

        /**
         * Sets the value of the cy property.
         * 
         */
        public void setCy(double value) {
            this.cy = value;
        }

        /**
         * Gets the value of the cz property.
         * 
         * @return
         *     possible object is
         *     {@link Double }
         *     
         */
        public Double getCz() {
            return cz;
        }

        /**
         * Sets the value of the cz property.
         * 
         * @param value
         *     allowed object is
         *     {@link Double }
         *     
         */
        public void setCz(Double value) {
            this.cz = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;attribute name="lat" use="required" type="{http://www.w3.org/2001/XMLSchema}double" />
     *       &lt;attribute name="lon" use="required" type="{http://www.w3.org/2001/XMLSchema}double" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class GPSCoordinates {

        @XmlAttribute(name = "lat", required = true)
        protected double lat;
        @XmlAttribute(name = "lon", required = true)
        protected double lon;

        /**
         * Gets the value of the lat property.
         * 
         */
        public double getLat() {
            return lat;
        }

        /**
         * Sets the value of the lat property.
         * 
         */
        public void setLat(double value) {
            this.lat = value;
        }

        /**
         * Gets the value of the lon property.
         * 
         */
        public double getLon() {
            return lon;
        }

        /**
         * Sets the value of the lon property.
         * 
         */
        public void setLon(double value) {
            this.lon = value;
        }

    }

}
